version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  win: golang:1.14.0-nanoserver-1809 

executors:
  exec_linux_go_1_12:
    docker:
      - image: circleci/golang:1.12.16
  exec_linux_go_1_13:
    docker:
      - image: circleci/golang:1.13.8
  exec_linux_go_1_14:
    docker:
      - image: circleci/golang:1.14.0

commands:
  install:
    description: "Install dependencies"
    steps:
      - run: GO111MODULE=on go mod vendor -v
  vet:
    description: "Run go vet"
    steps:
      - run: go vet github.com/cucumber/godog
      - run: go vet github.com/cucumber/godog/gherkin
      - run: go vet github.com/cucumber/godog/colors
  fmt:
    description: "Run go fmt"
    steps:
      - run: test -z "$(go fmt ./...)"
  lint:
    description: "Run golint"
    steps:
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./godog
      - run: golint ./cmd/godog/main.go
  godog:
    description: "Run godog"
    steps:
      - run: go install ./cmd/godog
      - run: godog -f progress
  go_test:
    description: "Run go test"
    steps:
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
  coverage:
    description: "Report on code coverage"
    steps:
      - codecov/upload:
          file: "coverage.txt"
  all:
    description: "Run all commands against godog code"
    steps:
      - checkout
      - install
      - vet
      - fmt
      - lint
      - godog
      - go_test
      - coverage

jobs:
  go_linux_1_12:
    working_directory: /go/src/github.com/cucumber/godog
    executor: exec_linux_go_1_12
    steps:
      - all
  go_linux_1_13:
    working_directory: /go/src/github.com/cucumber/godog
    executor: exec_linux_go_1_13
    steps:
      - all
  go_linux_1_14:
    working_directory: /go/src/github.com/cucumber/godog
    executor: exec_linux_go_1_14
    steps:
      - all
  go_nanoserver_1_14:
    working_directory: /go/src/github.com/cucumber/godog
    executor: win/default
    steps:
      - all

workflows:
  version: 2
  test:
    jobs:
      - go_linux_1_12
      - go_linux_1_13
      - go_linux_1_14
      - go_nanoserver_1_14
